shop_project/cart_app/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cart_app'
urlpatterns = [
    url(r'^$', views.load_cart, name='index'),
    # path('<int:category_id>/', views.category_details, name='category_details')

]

shop_project/categories/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'categories'
urlpatterns = [
    url(r'^$', views.load_categories, name='index'),
    path('<int:category_id>/', views.category_details, name='category_details')
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static

from shop_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^categories/', include('categories.urls')),
    url(r'^cart/', include('cart_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_project/cart_app/models.py
from django.db import models


class Cart(models.Model):
    user = models.ForeignKey('User', null=True, blank=True)
    products = models.ManyToManyField('products.Product', blank=True)
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

shop_project/categories/models.py
from django.db import models

from treebeard.mp_tree import MP_Node


class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500, default="")
    subcategory_key = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True)


class CategoryTree(MP_Node):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500, default="")
    node_order_by = ['name']

    def __unicode__(self):
        return 'Category: %s' % self.name

shop_project/product/models.py
from django.db import models


class Product(models.Model):
    """object that represent a product"""
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=500, default="")
    price = models.IntegerField()
    # TODO: set a default media folder
    picture = models.ImageField(blank=True)
    category_key = models.ForeignKey(
        'categories.CategoryTree', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

shop_project/cart_app/views.py
from django.shortcuts import render

# Create your views here.

shop_project/categories/views.py
from django.shortcuts import render
from django.views import generic
from .models import Category, CategoryTree
from product.models import Product


def load_categories(request):
    """links to a the list of categories"""
    final_list = list()

    def traverse_it(it):
        """traverse the input query and extract a list of pair of names and keys of categories"""
        if (isinstance(it, list)):
            for item in it:
                traverse_it(item)
        elif (isinstance(it, dict)):
            final_list.append({"name": it["data"]["name"], "id": it["id"]})
            for key in it:
                print("*"*50)
                print(it[key])
                print("*"*50)
                print(key)
                print("*"*50)
            if ("children" in it):
                print("adsa")
                for item in it["children"]:
                    traverse_it(item)

    frontned_template = "categories.html"
    items = dict()
    items = Category.objects.all()
    categories = CategoryTree.dump_bulk()
    traverse_it(categories)
    return render(request, frontned_template,
                  {"items": items, "categories": final_list})


def category_details(request, category_id):
    """links to a template of products related to current category"""
    frontned_template = "categories_details.html"
    products = Product.objects.filter(category_key__pk=category_id)
    # print("*"*80)
    # for product in products:
    #     print(product)
    # print("*"*80)
    output_dict = {"products": products, "category_id": category_id}
    return render(request, frontned_template, output_dict)

shop_project/categories/templates/categories.html
<html>
<h1>Categories</h1>
<ul>
    {% for category in items %}
    <ol>{{ category.name }}</ol>
    {% endfor %}
</ul>


<ul>
    {% for category in categories %}
    <ol>
        <a href="{% url 'categories:category_details' category.id %}">{{ category.name }}</a>
    </ol>
    {% endfor %}
</ul>



</html>

shop_project/categories/templates/categories_details.html
<html>
<h1>Category {{ category_id }}</h1>
{% for el in products %}
<p>
    <div>{{ el.name }}</div>
    <div>{{ el.price }}</div>
    <div>{{ el.description }}</div>
    {% if el.picture%}
    <!-- TODO: make it resizeable PILLOW -->
    <img src="{{ el.picture.url }}" alt=""> {% endif %}
</p>
{% endfor %}


</html>

shop_project/categories/templates/macro_attempt.html
<!-- recursive function to sort categories
{% macro traverse(categories) -%}
<ol></ol>
 {% if (isinstance(categories, list)) %}
        {% for category in categories %}
            <ol>{{ traverse(category) }}</ol>
        {% endfor %}
    {% endif %} -->
<!-- {% if (isinstance(categories, list)) %}
        {% for category in categories %}
            <ol>{{ traverse(category) }}</ol>
        {% endfor %}
    {% elif (isinstance(categories, dict)) %}
        <div>{{ el["data"]["name"] }}</div>
        {% if category["children"] %}
            <ol>
                 {% for el in category["children"] %}
                    <ol></ol>
                {% endfor %}
            </ol>
    {% endif %} -->
<!-- {%- endmacro %}  -->